version: "3"
services:
  db:
    image: mdsurem/blood:db
    ports:
      - "3306:3306"
    volumes:
      - "/var/www/html"

  app:
    image: mdsurem/blood:app
    ports:
      - "3434:80"
    depends_on:
      - db
    environment:
      - DB_HOST=db  # Make sure your app points to the 'db' service name for the database
